
###   Dunnit


```{r,echo=FALSE,eval=TRUE, fig.width=1.6, fig.height=.7,fig.align = "center",cache=TRUE, fig.show = "hold", out.width = "100%",message=FALSE,warning=FALSE}
library(tidyverse)
```


```{r,echo=FALSE,eval=TRUE, fig.width = 2, fig.height = 2,fig.align = "center",cache=TRUE, fig.show = "hold", out.width = "100%", message = FALSE, }
graphviz.plot(DunnitDAG)
source("..//utils//kableCPTs.R")
```





\begin{figure}
    \centering
    \begin{minipage}{0.4\textwidth}
        \centering
```{r,echo=FALSE,eval=TRUE,fig.align = "center",cache=TRUE, fig.show = "hold", out.width = "100%"}
CPkable1("DunnitBN","I")
``` 
\end{minipage}\hfill
    \begin{minipage}{0.4\textwidth}
        \centering
```{r,echo=FALSE,eval=TRUE,fig.align = "center",cache=TRUE, fig.show = "hold", out.width = "100%"}
CPkable1("DunnitBN","G")  
```
    \end{minipage}
  \end{figure}




\begin{figure}
    \centering
    \begin{minipage}{0.3\textwidth}
        \centering
```{r,echo=FALSE,eval=TRUE,fig.align = "center",cache=TRUE, fig.show = "hold", out.width = "100%"}
CPkable2("DunnitBN","W") 
```
    \end{minipage}\hfill
    \begin{minipage}{0.3\textwidth}
        \centering
```{r,echo=FALSE,eval=TRUE,fig.align = "center",cache=TRUE, fig.show = "hold", out.width = "100%"}
CPkable0("DunnitBN","T")  
```
    \end{minipage}
    \begin{minipage}{0.3\textwidth}
        \centering
```{r,echo=FALSE,eval=TRUE,fig.align = "center",cache=TRUE, fig.show = "hold", out.width = "100%"}
CPkable0("DunnitBN","M") 
```
    \end{minipage}
\end{figure}


```{r,echo=FALSE,eval=TRUE, fig.width=1.6, fig.height=.7,fig.align = "center",cache=TRUE, fig.show = "hold", out.width = "100%"}
tableLaTeX(DunnitTable)
tableLaTeX(DunnitResults)
```





